In [66]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None #學生的分數
scores_df:DataFrame | None = None #學生的分數的DataFrame
np.random.seed(42)  # 加在 randint 之前
scores=np.random.randint(50,101, size=(50,5))
#scores
#print(type(scores))
#print(scores.shape)
scores_df=pd.DataFrame(scores,
         columns=['國文','英文','數學','地理','歷史'],
         index=range(1,51))
#scores_df.T
names_df:DataFrame=pd.read_csv('students.csv')
#type(names_df['姓名'])
scores_df[['姓名','性別']]=names_df[['姓名','性別']].head(n=50).values
scores_df=scores_df[['姓名','性別','國文','英文','數學','地理','歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
#slice寫法
scores_df.iloc[5:10]
#scores_df[scores_df['姓名']=='鄧文龍']
#scores_df[scores_df['國文']<60]
#display(scores_df.query("性別=='男' and 國文<60"))
test_df=scores_df.query("性別=='女' and 國文<60")
test_df=scores_df[['國文','英文','數學','地理','歷史']]
scores_df["總分"]=scores_df[['國文','英文','數學','地理','歷史']].sum(axis=1)
scores_df["平均"]=scores_df[['國文','英文','數學','地理','歷史']].mean(axis=1)
#display(scores_df.query("平均>80"))
scores_df["排名"]=scores_df["總分"].rank(ascending=False,method='min')
scores_df.sort_values(by='排名')

     姓名 性別   國文   英文   數學  地理   歷史   總分    平均    排名
41  毛文龍  男   86   82  100  91   93  452  90.4   1.0
43  簡國誠  男   90   98   98  61   88  435  87.0   2.0
8   張惠敏  女   96  100   93  52   86  427  85.4   3.0
33  高家豪  男   79   86   72  88   94  419  83.8   4.0
27  胡國亮  男   84   93   89  71   76  413  82.6   5.0
19  趙志偉  男   96   73   75  74   94  412  82.4   6.0
37  溫俊賢  男   77   93   93  69   79  411  82.2   7.0
26  許喬茵  女   82   97   72  73   86  410  82.0   8.0
32  胡淑惠  女   81   88   98  81   53  401  80.2   9.0
28  萬雅玲  女   84   50   84  86   96  400  80.0  10.0
24  鄧昕穎  女   54   91   88  90   77  400  80.0  10.0
12  江筠雅  女   96   56   93  57   96  398  79.6  12.0
13  孟冠霖  男   84   63   66  85   99  397  79.4  13.0
6   鄭語桐  女   61   71   93  74   98  397  79.4  13.0
31  莫家維  男   64   75   91  62  100  392  78.4  15.0
18  徐雅惠  女   89   70   65  94   67  385  77.0  16.0
44  曹曉君  女   51   52   98  86   98  385  77.0  16.0
35  鄧文龍  男   81   56  100  71   77  385  77.0  16.0
22  方芷萱  女   93   57   73  60  100  383  76.6  19.0
38  何淑惠  女   60   77   74  88   82  381  76.2  20.0
34  戴曉君  女   64   92   78  85   62  381  76.2  20.0
3   簡冠霖  男   60   73   85  89   73  380  76.0  22.0
1   嚴國棟  男   88   78   64  92   57  379  75.8  23.0
20  鄭曉君  女   90   78   64  94   50  376  75.2  24.0
50  余雅芳  女   71   60   97  65   82  375  75.0  25.0
23  鍾志豪  男   66   57   84  84   82  373  74.6  26.0
7   宋承翰  男   76   91   77  65   64  373  74.6  26.0
9   蕭家維  男  100   56   70  58   88  372  74.4  28.0
42  葉昕穎  女   73   64   81  81   73  372  74.4  28.0
46  范琬婷  女   72   86   81  82   50  371  74.2  30.0
16  周淑惠  女   83   59   85  63   80  370  74.0  31.0
5   向文智  男   79   87   51  70   82  369  73.8  32.0
47  羅文祥  男   68   51   93  75   81  368  73.6  33.0
36  馮淑麗  女   51   91   94  55   77  368  73.6  33.0
15  游俊傑  男   53   78   67  75   93  366  73.2  35.0
2   張曉君  女   70   88   68  72   60  358  71.6  36.0
10  葉芷萱  女   67   53   74  63   99  356  71.2  37.0
17  趙澤宇  男   97   64   57  63   72  353  70.6  38.0
49  高承翰  男   87   73   54  83   55  352  70.4  39.0
30  蔡雅文  女   63   88   76  58   64  349  69.8  40.0
45  彭文龍  男   66   98   51  51   77  343  68.6  41.0
4   廖雅芬  女   52   71   51  73   93  340  68.0  42.0
14  尹語桐  女   89   53   51  55   91  339  67.8  43.0
40  覃曉萍  女   88   55   57  76   58  334  66.8  44.0
39  陸文祥  男   50   76   62  90   52  330  66.0  45.0
11  張家弘  男   58   75   51  69   77  330  66.0  45.0
25  曾志強  男   56   58   57  61   83  315  63.0  47.0
48  盧怡萱  女   55   81   53  60   66  315  63.0  47.0
21  謝俊賢  男   74   56   58  73   50  311  62.2  49.0
29  史宏達  男   63   52   50  54   75  294  58.8  50.0

In [67]:
from pandas import Series
def calculator(s:Series) -> int :
    n=((s<60).sum())
    return n

scores_df['不及格的科目數']=scores_df[['國文','英文','數學','地理','歷史']].apply(calculator,axis=1)
scores_df

     姓名 性別   國文   英文   數學  地理   歷史   總分    平均    排名  不及格的科目數
1   嚴國棟  男   88   78   64  92   57  379  75.8  23.0        1
2   張曉君  女   70   88   68  72   60  358  71.6  36.0        0
3   簡冠霖  男   60   73   85  89   73  380  76.0  22.0        0
4   廖雅芬  女   52   71   51  73   93  340  68.0  42.0        2
5   向文智  男   79   87   51  70   82  369  73.8  32.0        1
6   鄭語桐  女   61   71   93  74   98  397  79.4  13.0        0
7   宋承翰  男   76   91   77  65   64  373  74.6  26.0        0
8   張惠敏  女   96  100   93  52   86  427  85.4   3.0        1
9   蕭家維  男  100   56   70  58   88  372  74.4  28.0        2
10  葉芷萱  女   67   53   74  63   99  356  71.2  37.0        1
11  張家弘  男   58   75   51  69   77  330  66.0  45.0        2
12  江筠雅  女   96   56   93  57   96  398  79.6  12.0        2
13  孟冠霖  男   84   63   66  85   99  397  79.4  13.0        0
14  尹語桐  女   89   53   51  55   91  339  67.8  43.0        3
15  游俊傑  男   53   78   67  75   93  366  73.2  35.0        1
16  周淑惠  女   83   59   85  63   80  370  74.0  31.0        1
17  趙澤宇  男   97   64   57  63   72  353  70.6  38.0        1
18  徐雅惠  女   89   70   65  94   67  385  77.0  16.0        0
19  趙志偉  男   96   73   75  74   94  412  82.4   6.0        0
20  鄭曉君  女   90   78   64  94   50  376  75.2  24.0        1
21  謝俊賢  男   74   56   58  73   50  311  62.2  49.0        3
22  方芷萱  女   93   57   73  60  100  383  76.6  19.0        1
23  鍾志豪  男   66   57   84  84   82  373  74.6  26.0        1
24  鄧昕穎  女   54   91   88  90   77  400  80.0  10.0        1
25  曾志強  男   56   58   57  61   83  315  63.0  47.0        3
26  許喬茵  女   82   97   72  73   86  410  82.0   8.0        0
27  胡國亮  男   84   93   89  71   76  413  82.6   5.0        0
28  萬雅玲  女   84   50   84  86   96  400  80.0  10.0        1
29  史宏達  男   63   52   50  54   75  294  58.8  50.0        3
30  蔡雅文  女   63   88   76  58   64  349  69.8  40.0        1
31  莫家維  男   64   75   91  62  100  392  78.4  15.0        0
32  胡淑惠  女   81   88   98  81   53  401  80.2   9.0        1
33  高家豪  男   79   86   72  88   94  419  83.8   4.0        0
34  戴曉君  女   64   92   78  85   62  381  76.2  20.0        0
35  鄧文龍  男   81   56  100  71   77  385  77.0  16.0        1
36  馮淑麗  女   51   91   94  55   77  368  73.6  33.0        2
37  溫俊賢  男   77   93   93  69   79  411  82.2   7.0        0
38  何淑惠  女   60   77   74  88   82  381  76.2  20.0        0
39  陸文祥  男   50   76   62  90   52  330  66.0  45.0        2
40  覃曉萍  女   88   55   57  76   58  334  66.8  44.0        3
41  毛文龍  男   86   82  100  91   93  452  90.4   1.0        0
42  葉昕穎  女   73   64   81  81   73  372  74.4  28.0        0
43  簡國誠  男   90   98   98  61   88  435  87.0   2.0        0
44  曹曉君  女   51   52   98  86   98  385  77.0  16.0        2
45  彭文龍  男   66   98   51  51   77  343  68.6  41.0        2
46  范琬婷  女   72   86   81  82   50  371  74.2  30.0        1
47  羅文祥  男   68   51   93  75   81  368  73.6  33.0        1
48  盧怡萱  女   55   81   53  60   66  315  63.0  47.0        2
49  高承翰  男   87   73   54  83   55  352  70.4  39.0        2
50  余雅芳  女   71   60   97  65   82  375  75.0  25.0        0

In [ ]:
def get_failing_subjects(row):
    subjects=['國文','英文','數學','地理','歷史']
    failing=[subj for subj in subjects if row[subj] < 60] #list綜合表達式
    fallings=['國文','英文','數學']
    return ','.join(failing) if failing else "無"

scores_df["不及格的科目名稱"]=scores_df[['國文','英文','數學','地理','歷史']].apply(get_failing_subjects,axis=1)
scores_df

     姓名 性別   國文   英文   數學  地理   歷史   總分    平均    排名  不及格的科目數  不及格的科目名稱
1   嚴國棟  男   88   78   64  92   57  379  75.8  23.0        1        歷史
2   張曉君  女   70   88   68  72   60  358  71.6  36.0        0         無
3   簡冠霖  男   60   73   85  89   73  380  76.0  22.0        0         無
4   廖雅芬  女   52   71   51  73   93  340  68.0  42.0        2     國文,數學
5   向文智  男   79   87   51  70   82  369  73.8  32.0        1        數學
6   鄭語桐  女   61   71   93  74   98  397  79.4  13.0        0         無
7   宋承翰  男   76   91   77  65   64  373  74.6  26.0        0         無
8   張惠敏  女   96  100   93  52   86  427  85.4   3.0        1        地理
9   蕭家維  男  100   56   70  58   88  372  74.4  28.0        2     英文,地理
10  葉芷萱  女   67   53   74  63   99  356  71.2  37.0        1        英文
11  張家弘  男   58   75   51  69   77  330  66.0  45.0        2     國文,數學
12  江筠雅  女   96   56   93  57   96  398  79.6  12.0        2     英文,地理
13  孟冠霖  男   84   63   66  85   99  397  79.4  13.0        0         無
14  尹語桐  女   89   53   51  55   91  339  67.8  43.0        3  英文,數學,地理
15  游俊傑  男   53   78   67  75   93  366  73.2  35.0        1        國文
16  周淑惠  女   83   59   85  63   80  370  74.0  31.0        1        英文
17  趙澤宇  男   97   64   57  63   72  353  70.6  38.0        1        數學
18  徐雅惠  女   89   70   65  94   67  385  77.0  16.0        0         無
19  趙志偉  男   96   73   75  74   94  412  82.4   6.0        0         無
20  鄭曉君  女   90   78   64  94   50  376  75.2  24.0        1        歷史
21  謝俊賢  男   74   56   58  73   50  311  62.2  49.0        3  英文,數學,歷史
22  方芷萱  女   93   57   73  60  100  383  76.6  19.0        1        英文
23  鍾志豪  男   66   57   84  84   82  373  74.6  26.0        1        英文
24  鄧昕穎  女   54   91   88  90   77  400  80.0  10.0        1        國文
25  曾志強  男   56   58   57  61   83  315  63.0  47.0        3  國文,英文,數學
26  許喬茵  女   82   97   72  73   86  410  82.0   8.0        0         無
27  胡國亮  男   84   93   89  71   76  413  82.6   5.0        0         無
28  萬雅玲  女   84   50   84  86   96  400  80.0  10.0        1        英文
29  史宏達  男   63   52   50  54   75  294  58.8  50.0        3  英文,數學,地理
30  蔡雅文  女   63   88   76  58   64  349  69.8  40.0        1        地理
31  莫家維  男   64   75   91  62  100  392  78.4  15.0        0         無
32  胡淑惠  女   81   88   98  81   53  401  80.2   9.0        1        歷史
33  高家豪  男   79   86   72  88   94  419  83.8   4.0        0         無
34  戴曉君  女   64   92   78  85   62  381  76.2  20.0        0         無
35  鄧文龍  男   81   56  100  71   77  385  77.0  16.0        1        英文
36  馮淑麗  女   51   91   94  55   77  368  73.6  33.0        2     國文,地理
37  溫俊賢  男   77   93   93  69   79  411  82.2   7.0        0         無
38  何淑惠  女   60   77   74  88   82  381  76.2  20.0        0         無
39  陸文祥  男   50   76   62  90   52  330  66.0  45.0        2     國文,歷史
40  覃曉萍  女   88   55   57  76   58  334  66.8  44.0        3  英文,數學,歷史
41  毛文龍  男   86   82  100  91   93  452  90.4   1.0        0         無
42  葉昕穎  女   73   64   81  81   73  372  74.4  28.0        0         無
43  簡國誠  男   90   98   98  61   88  435  87.0   2.0        0         無
44  曹曉君  女   51   52   98  86   98  385  77.0  16.0        2     國文,英文
45  彭文龍  男   66   98   51  51   77  343  68.6  41.0        2     數學,地理
46  范琬婷  女   72   86   81  82   50  371  74.2  30.0        1        歷史
47  羅文祥  男   68   51   93  75   81  368  73.6  33.0        1        英文
48  盧怡萱  女   55   81   53  60   66  315  63.0  47.0        2     國文,數學
49  高承翰  男   87   73   54  83   55  352  70.4  39.0        2     數學,歷史
50  余雅芳  女   71   60   97  65   82  375  75.0  25.0        0         無