In [32]:
import pandas as pd
import numpy as np

data=pd.Series(np.random.randn(9),
                   index=[['a','a','a','b','b','c','c','d','d'],
                          [1,2,3,1,2,3,1,2,3]])

data

a  1   -1.134930
   2   -0.532841
   3   -1.632312
b  1   -0.214115
   2   -1.866236
c  3    0.608683
   1   -0.161434
d  2    0.483501
   3   -0.450929
dtype: float64

In [33]:
data1=data.unstack()
data1

          1         2         3
a -1.134930 -0.532841 -1.632312
b -0.214115 -1.866236       NaN
c -0.161434       NaN  0.608683
d       NaN  0.483501 -0.450929

In [34]:
data1.stack()

a  1   -1.134930
   2   -0.532841
   3   -1.632312
b  1   -0.214115
   2   -1.866236
   3         NaN
c  1   -0.161434
   2         NaN
   3    0.608683
d  1         NaN
   2    0.483501
   3   -0.450929
dtype: float64

In [38]:
import numpy as np
import pandas as pd

frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                    index=[['a','a','b','b'],[1, 2, 1, 2]],
                    columns=[['台北','台北','台中'],['Green','Red','Green']])
frame.index.names = ['key1', 'key2']
frame.columns.names = ['縣市','顏色']
frame

縣市           台北        台中
顏色        Green Red Green
key1 key2
a    1        0   1     2
     2        3   4     5
b    1        6   7     8
     2        9  10    11

In [39]:
frame1 = frame.stack(['顏色','縣市'])
frame1

key1  key2  顏色     縣市
a     1     Green  台北     0
            Red    台北     1
            Green  台中     2
      2     Green  台北     3
            Red    台北     4
            Green  台中     5
b     1     Green  台北     6
            Red    台北     7
            Green  台中     8
      2     Green  台北     9
            Red    台北    10
            Green  台中    11
dtype: int64

In [41]:
frame1.unstack('key1')

key1           a   b
key2 顏色    縣市
1    Green 台中  2   8
           台北  0   6
     Red   台北  1   7
2    Green 台中  5  11
           台北  3   9
     Red   台北  4  10