In [7]:
import pandas as pd

dataFrame = pd.read_csv('各鄉鎮市區人口密度.csv')
dataFrame.columns=["統計年","區域別","年底人囗數","土地面積","人口密碼"]#改變欄位
df=dataFrame.drop(index=0)
df1=df.dropna(axis=0,how='any')
#df1
#df2=df1.drop(columns=["統計年"])
df2=df1.drop(['統計年'], axis=1)
df2

        區域別   年底人囗數     土地面積   人口密碼
1    新北市板橋區  551480  23.1373  23835
2    新北市三重區  387484   16.317  23747
3    新北市中和區  413590   20.144  20532
4    新北市永和區  222585   5.7138  38956
5    新北市新莊區  416524  19.7383  21102
..      ...     ...      ...    ...
366  連江縣北竿鄉    2360      9.9    238
367  連江縣莒光鄉    1624      4.7    346
368  連江縣東引鄉    1352      3.8    356
369    東沙群島      …      2.38     …
370    南沙群島      …    0.5045     …

[370 rows x 4 columns]

In [9]:
import pandas as pd

dataFrame = pd.read_csv('各鄉鎮市區人口密度.csv')
dataFrame.columns = ["統計年", "區域別", "年底人口數", "土地面積", "人口密碼"]

# 把年底人口數轉成數字，無法轉換的變成 NaN
dataFrame["年底人口數"] = pd.to_numeric(dataFrame["年底人口數"], errors="coerce")

# 篩選：年底人口數不是空值、不是 0
df = dataFrame[(dataFrame["年底人口數"].notna()) & (dataFrame["年底人口數"] != 0)]

# 去掉統計年欄位
df2 = df.drop(["統計年"], axis=1)

print(df2)
df2.info()

        區域別     年底人口數     土地面積   人口密碼
1    新北市板橋區  551480.0  23.1373  23835
2    新北市三重區  387484.0   16.317  23747
3    新北市中和區  413590.0   20.144  20532
4    新北市永和區  222585.0   5.7138  38956
5    新北市新莊區  416524.0  19.7383  21102
..      ...       ...      ...    ...
364  金門縣烏坵鄉     685.0      1.2    571
365  連江縣南竿鄉    7544.0     10.4    725
366  連江縣北竿鄉    2360.0      9.9    238
367  連江縣莒光鄉    1624.0      4.7    346
368  連江縣東引鄉    1352.0      3.8    356

[368 rows x 4 columns]
<class 'pandas.DataFrame'>
RangeIndex: 368 entries, 1 to 368
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   區域別     368 non-null    str
 1   年底人口數   368 non-null    float64
 2   土地面積    368 non-null    str
 3   人口密碼    368 non-null    str
dtypes: float64(1), str(3)
memory usage: 21.9 KB

In [11]:
dataFrame.columns = ["統計年", "區域別", "年底人口數", "土地面積", "人口密度"] #改變欄位名稱
df = dataFrame.drop(index=0)
# 1. 移除統計年
df2 = df.drop('統計年', axis=1)
df2
# 2. 將「年底人口數」強制轉為數字，像 '…' 這樣的文字會被強制變成 NaN
df2["年底人口數"] = pd.to_numeric(df2["年底人口數"], errors="coerce")
df2
# 3. 這時候再用 dropna()，就能把原本是 '…' 的東沙、南沙群島（以及其他原本就是 NaN 的列）一次清乾淨！
df2 = df2.dropna(subset=["年底人口數"])
df2.info()
# # 4. 最後順利轉換為整數
df2["年底人口數"] = df2["年底人口數"].astype("int64")
df2["土地面積"] = df2["土地面積"].astype("float")
df2["人口密度"] = df2["人口密度"].astype("int64")
df2

<class 'pandas.DataFrame'>
RangeIndex: 368 entries, 1 to 368
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   區域別     368 non-null    str
 1   年底人口數   368 non-null    float64
 2   土地面積    368 non-null    str
 3   人口密度    368 non-null    str
dtypes: float64(1), str(3)
memory usage: 21.9 KB

        區域別   年底人口數     土地面積   人口密度
1    新北市板橋區  551480  23.1373  23835
2    新北市三重區  387484  16.3170  23747
3    新北市中和區  413590  20.1440  20532
4    新北市永和區  222585   5.7138  38956
5    新北市新莊區  416524  19.7383  21102
..      ...     ...      ...    ...
364  金門縣烏坵鄉     685   1.2000    571
365  連江縣南竿鄉    7544  10.4000    725
366  連江縣北竿鄉    2360   9.9000    238
367  連江縣莒光鄉    1624   4.7000    346
368  連江縣東引鄉    1352   3.8000    356

[368 rows x 4 columns]

In [12]:
import pandas as pd
import numpy as np

# 讀取 CSV 檔
dataFrame = pd.read_csv('各班圖書借閱統計.csv')

# 第 0 列(index 為 0)才是真正的中文欄位名稱,把它設為欄位名
dataFrame.columns = dataFrame.loc[0]

# 刪除第 0 列(已經拿來當欄位名,資料中不需要重複)
dataFrame = dataFrame.drop(0)

# 刪除合計列與 4 列說明文字
dataFrame.drop([dataFrame.index[-5], dataFrame.index[-4], dataFrame.index[-3], dataFrame.index[-2], dataFrame.index[-1]], inplace=True)

# 取得目前的列數與欄數
rowCount, columnCount = dataFrame.shape

# 把索引重設為從 0 開始的連續編號
dataFrame.index = range(rowCount)

# 只保留「班級」「學生人數」「借閱冊數」三個欄位
dataFrame1 = dataFrame.reindex(columns=['班級', '學生人數', '借閱冊數'])

print(dataFrame1)

0    班級 學生人數 借閱冊數
0  一年甲班   35  420
1  一年乙班   33  264
2  一年丙班   34  510
3  二年甲班   36  288
4  二年乙班   32  480
5  二年丙班   35  245
6  三年甲班   30  600
7  三年乙班   31  372
8  三年丙班   33  198

In [14]:
import pandas as pd
import tkinter as tk
from tkinter import ttk

# =========================
# 資料處理
# =========================
def load_data():
    # 讀取 CSV 檔
    df = pd.read_csv('各鄉鎮市區人口密度.csv')

    # 將第一列作為欄位名稱，並移除第一列
    df.columns = df.iloc[0]
    df = df.drop(0)

    # 移除最後 5 筆非資料內容（尾部說明資訊）
    df = df.iloc[:-5]

    # 只保留需要的三個欄位，並將「年底人口數」改名為「人口數」
    df = df[['區域別', '年底人口數', '土地面積']].rename(columns={'年底人口數': '人口數'})

    # 轉成數值型態，無法轉換的資料變成 NaN
    df['人口數'] = pd.to_numeric(df['人口數'], errors='coerce')
    df['土地面積'] = pd.to_numeric(df['土地面積'], errors='coerce')

    # 移除含有空值的列
    df = df.dropna()

    # 新增人口密度欄位
    df['人口密度'] = df['人口數'] / df['土地面積']

    return df


# =========================
# Treeview 排序功能
# =========================
def sort_treeview(col):
    global sort_reverse

    # 取出 Treeview 目前所有資料
    data = []
    for item in tree.get_children(''):
        values = tree.item(item, 'values')
        data.append((values, item))

    # 根據欄位決定排序方式
    col_index = columns.index(col)

    def sort_key(x):
        value = x[0][col_index]
        try:
            return float(value)
        except ValueError:
            return str(value)

    data.sort(key=sort_key, reverse=sort_reverse)

    # 重新排列 Treeview 項目
    for index, (_, item) in enumerate(data):
        tree.move(item, '', index)

    # 每次點擊後切換升冪 / 降冪
    sort_reverse = not sort_reverse


# =========================
# 顯示資料
# =========================
def show_data(df_show):
    # 清空表格
    for item in tree.get_children():
        tree.delete(item)

    # 顯示資料
    for _, row in df_show.iterrows():
        tree.insert(
            '',
            tk.END,
            values=(
                row['區域別'],
                f"{int(row['人口數'])}",
                f"{row['土地面積']:.4f}",
                f"{row['人口密度']:.2f}"
            )
        )


# =========================
# 查詢功能
# =========================
def search_data():
    keyword = entry.get().strip()

    if keyword == "":
        result = dataFrame
    else:
        result = dataFrame[dataFrame['區域別'].astype(str).str.contains(keyword, na=False)]

    show_data(result)


# =========================
# 主程式
# =========================
dataFrame = load_data()

root = tk.Tk()
root.title('台灣鄉鎮市區人口密度查詢系統')
root.geometry('900x600')

# 排序方向控制
sort_reverse = False

# 上方控制區
control_frame = tk.Frame(root)
control_frame.pack(fill='x', padx=10, pady=10)

label = tk.Label(control_frame, text='輸入區域名稱：')
label.pack(side='left')

entry = tk.Entry(control_frame, width=30)
entry.pack(side='left', padx=5)

button = tk.Button(control_frame, text='查詢', command=search_data)
button.pack(side='left', padx=5)

# 下方表格區
table_frame = tk.Frame(root)
table_frame.pack(fill='both', expand=True, padx=10, pady=10)

columns = ('區域別', '人口數', '土地面積', '人口密度')
tree = ttk.Treeview(table_frame, columns=columns, show='headings')

# 設定欄位標題與欄寬，點欄位可排序
for col in columns:
    tree.heading(col, text=col, command=lambda c=col: sort_treeview(c))
    tree.column(col, width=180, anchor='center')

# 垂直捲軸
scrollbar_y = ttk.Scrollbar(table_frame, orient='vertical', command=tree.yview)
tree.configure(yscrollcommand=scrollbar_y.set)

tree.pack(side='left', fill='both', expand=True)
scrollbar_y.pack(side='right', fill='y')

# 啟動時顯示全部資料
show_data(dataFrame)

root.mainloop()